title: "Micah Juiye's Website"
description: "My Personal website"
author: "Micah Juiye"
url: "https://micah-juiye.github.io"
theme: minima

minima:
  skin: dark
  include:
    - "/assets/css/custom.css"  # Link to custom CSS

# Social links
social_links:
  - { platform: github, user_url: "https://github.com/micah-juiye" }
  - { platform: linkedin, user_url: "https://linkedin.com/in/micah-juiye" }
  - { platform: instagram, user_url: "https://instagram.com/yourusername" }

# Plugins and SASS configuration
plugins:
  - jekyll-sass-converter

sass:
  style: compressed

markdown: kramdown
