title: "Micah Juiye's Website"
description: "My Personal website"
author: "Micah Juiye"
url: "https://micah-juiye.github.io"
theme: minima

# Optional theme settings
minima:
  skin: dark
# Generate social links in footer.
social_links:
  - { platform: github,    user_url: "https://github.com/micah-juiye" }
  - { platform: linkedin,  user_url: "https://linkedin.com/in/micah-juiye" }
  - { platform: instagram, user_url: "https://instagram.com/yourusername" }
# _config.yml

plugins:
  - jekyll-sass-converter

sass:
  style: compressed

markdown: kramdown

# Include the custom CSS file
css:
  - "/assets/css/custom.css"

